openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3

paths:
  /register:
    post:
      summary: Add a new user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegisterReqBody'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
  /deposit:
    post:
      summary: Deposit some amount
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TransactionReqBody'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
        '404':
          description: User not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserNotFoundResponse'
  /withdraw:
    post:
      summary: Withdraw some amount
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TransactionReqBody'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
        '404':
          description: User not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserNotFoundResponse'
        '406':
          description: Cannot withdraw because the balance will be negative error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CannotWithdrawResponse'
components:
  schemas:
    RegisterReqBody:
      type: object
      properties:
        name:
          type: string
          example: Michael
    TransactionReqBody:
      type: object
      properties:
        userId:
          type: integer
          example: 1
        amount:
          type: integer
          format: double
          example: 500.25
    RegisterResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Michael
        balance:
          type: string
          format: double
          example: 500.25
        created_at:
          type: string
          format: date-time
          example: "2022-12-02T18:43:33.000+07:00"
        updated_at:
          type: string
          format: date-time
          example: "2022-12-02T18:43:33.000+07:00"
    TransactionResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Michael
        balance:
          type: string
          format: double
          example: 500.25
        created_at:
          type: string
          format: date-time
          example: "2022-12-02T18:43:33.000+07:00"
        updated_at:
          type: string
          format: date-time
          example: "2022-12-02T18:43:33.000+07:00"
        current_balance:
          type: string
          format: double
          example: 500.25
    ValidationResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              rule:
                type: string
                example: required
              field:
                type: string
                field: name
              message:
                type: string
                example: required validation failed
    UserNotFoundResponse:
      type: object
      properties:
        message:
          type: string
          example: User not found
    CannotWithdrawResponse:
      type: object
      properties:
        message:
          type: string
          example: "Cannot over-withdraw / having negative balance. Current balance: 0.00"
        current_balance:
          type: string
          format: double
          example: "0.00"